<?php
$title = 'Add new usuario';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
    <?php
$form = $this->form;
$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'));
echo $this->formRow($form->get('senha'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>

        <a href="<?php echo $this->url('usuario', array('action'=>'index'));?>">Cancel</a>