<?php
$title = 'usuarios';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('usuario', array('action'=>'add'));?>">Add new user</a>
</p>

<table class="table">
<tr>
    <th>Nome</th>
    <th>Senha</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($usuarios as $usuario) : ?>
<tr>
    <td><?php echo $this->escapeHtml($usuario->nome);?></td>
    <td><?php echo $this->escapeHtml($usuario->senha);?></td>
    <td>
        <a href="<?php echo $this->url('usuario',
            array('action'=>'edit', 'id' => $usuario->id));?>">Edit</a>
        <a href="<?php echo $this->url('usuario',
            array('action'=>'delete', 'id' => $usuario->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>