<?php

$title = 'Delete bits';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($bits->title); ?>' by
    '<?php echo $this->escapeHtml($bits->artist); ?>'?
</p>
<?php
$url = $this->url('bits', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $bits->id; ?>" />
    <input type="submit" name="del" value="Sim" />
    <input type="submit" name="del" value="Não" />
</div>
</form>