<?php

$title = 'Edit bits';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'bits',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('codigo'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

?>

<a href="<?php echo $this->url('bits', array('action'=>'index'));?>">Cancel</a>